clc
currentpath = pwd;
cd src
<<<<<<< HEAD
mexcuda -I../include ./mex_McSART.cu host_load_field.cu ...
=======
mexcuda -I../include ./SART_cuda.cu host_load_field.cu ...
>>>>>>> 7f9f4366d3c0653b395c1a7c8b31341946826fbd
    kernel_add.cu kernel_backprojection.cu kernel_deformation.cu ...
    host_deformation.cu kernel_division.cu kernel_initial.cu...
    kernel_projection.cu kernel_update.cu kernel_forwardDVF.cu...
    kernel_invertDVF.cu processBar.cu -lcublas  -outdir ../bin 
cd(currentpath)
