clc
% currentpath = pwd;
% cd src
mexcuda -Iinclude src/SART_cuda.cu src/host_load_field.cu ...
    src/kernel_add.cu src/kernel_backprojection.cu src/kernel_deformation.cu ...
    src/host_deformation.cu src/kernel_division.cu src/kernel_initial.cu...
    src/kernel_projection.cu src/kernel_update.cu src/kernel_forwardDVF.cu...
    src/kernel_invertDVF.cu src/processBar.cu -lcublas  -outdir bin 
% cd(currentpath)
